# Generated by Django 5.1.15 on 2026-08-12 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='primary_editor',
            field=models.ForeignKey(help_text='Primary editor responsible for this publisher', limit_choices_to={'role__in': ['editor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Editors who can approve articles for this publisher', limit_choices_to={'role__in': ['editor']}, related_name='editor_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, help_text='Journalists who write for this publisher', limit_choices_to={'role__in': ['journalist']}, related_name='journalist_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
